meta_product_name: "Relax mass'"
meta_title: "Relax mass' - Le réseau de confiance pour réserver un massage à domicile"
meta_description: "Relax Mass' est la solution en ligne pour réserver un massage à domicile. Consultez la liste de nos massothérapeuthes, des professionnels certifiés et évalués par la communauté Relax Mass'."
meta_image: "massage_01-green-1200x630.jpg" # should exist in `app/assets/images/`
